stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - cd app
    - cp Interview/settings.py.testing Interview/settings.py
    - pip3 install -r requirements.txt
    - python3 manage.py test
