services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: "interview"
  MYSQL_ROOT_PASSWORD: "nomoreinterview"

stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip libmariadb-dev-compat libmariadb-dev
    - cd app
    - cp Interview/settings.py.testing Interview/settings.py
    - pip3 install -r requirements.txt
    - python3 manage.py test
